# TypeScript-specific configuration
npmName: my-api-client
npmVersion: 1.0.0
supportsES6: true
withInterfaces: true
modelPropertyNaming: camelCase
enumPropertyNaming: UPPERCASE
useSingleRequestParameter: false