/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as ResendOTP from "../ResendOTP.js";
import type * as ResendOTPPasswordReset from "../ResendOTPPasswordReset.js";
import type * as auth from "../auth.js";
import type * as authDefinitions_index from "../authDefinitions/index.js";
import type * as blogs from "../blogs.js";
import type * as blogsDefinitions_index from "../blogsDefinitions/index.js";
import type * as blogsDefinitions_mutations_archiveBlog from "../blogsDefinitions/mutations/archiveBlog.js";
import type * as blogsDefinitions_mutations_bookmarkBlog from "../blogsDefinitions/mutations/bookmarkBlog.js";
import type * as blogsDefinitions_mutations_createBlog from "../blogsDefinitions/mutations/createBlog.js";
import type * as blogsDefinitions_mutations_createComment from "../blogsDefinitions/mutations/createComment.js";
import type * as blogsDefinitions_mutations_deleteBlog from "../blogsDefinitions/mutations/deleteBlog.js";
import type * as blogsDefinitions_mutations_deleteComment from "../blogsDefinitions/mutations/deleteComment.js";
import type * as blogsDefinitions_mutations_featureBlog from "../blogsDefinitions/mutations/featureBlog.js";
import type * as blogsDefinitions_mutations_flagBlog from "../blogsDefinitions/mutations/flagBlog.js";
import type * as blogsDefinitions_mutations_flagComment from "../blogsDefinitions/mutations/flagComment.js";
import type * as blogsDefinitions_mutations_index from "../blogsDefinitions/mutations/index.js";
import type * as blogsDefinitions_mutations_likeBlog from "../blogsDefinitions/mutations/likeBlog.js";
import type * as blogsDefinitions_mutations_likeComment from "../blogsDefinitions/mutations/likeComment.js";
import type * as blogsDefinitions_mutations_moderateBlog from "../blogsDefinitions/mutations/moderateBlog.js";
import type * as blogsDefinitions_mutations_pinBlog from "../blogsDefinitions/mutations/pinBlog.js";
import type * as blogsDefinitions_mutations_publishBlog from "../blogsDefinitions/mutations/publishBlog.js";
import type * as blogsDefinitions_mutations_reviewFlag from "../blogsDefinitions/mutations/reviewFlag.js";
import type * as blogsDefinitions_mutations_shareBlog from "../blogsDefinitions/mutations/shareBlog.js";
import type * as blogsDefinitions_mutations_unbookmarkBlog from "../blogsDefinitions/mutations/unbookmarkBlog.js";
import type * as blogsDefinitions_mutations_unlikeBlog from "../blogsDefinitions/mutations/unlikeBlog.js";
import type * as blogsDefinitions_mutations_unpublishBlog from "../blogsDefinitions/mutations/unpublishBlog.js";
import type * as blogsDefinitions_mutations_updateBlog from "../blogsDefinitions/mutations/updateBlog.js";
import type * as blogsDefinitions_mutations_uploadBlogCover from "../blogsDefinitions/mutations/uploadBlogCover.js";
import type * as blogsDefinitions_mutations_viewBlog from "../blogsDefinitions/mutations/viewBlog.js";
import type * as blogsDefinitions_queries_getBlogBySlug from "../blogsDefinitions/queries/getBlogBySlug.js";
import type * as blogsDefinitions_queries_getBlogFlags from "../blogsDefinitions/queries/getBlogFlags.js";
import type * as blogsDefinitions_queries_getBlogOverallStats from "../blogsDefinitions/queries/getBlogOverallStats.js";
import type * as blogsDefinitions_queries_getBlogStats from "../blogsDefinitions/queries/getBlogStats.js";
import type * as blogsDefinitions_queries_getBlogs from "../blogsDefinitions/queries/getBlogs.js";
import type * as blogsDefinitions_queries_getCategories from "../blogsDefinitions/queries/getCategories.js";
import type * as blogsDefinitions_queries_getCommentReplies from "../blogsDefinitions/queries/getCommentReplies.js";
import type * as blogsDefinitions_queries_getCommentsForBlog from "../blogsDefinitions/queries/getCommentsForBlog.js";
import type * as blogsDefinitions_queries_getFeaturedBlogs from "../blogsDefinitions/queries/getFeaturedBlogs.js";
import type * as blogsDefinitions_queries_getMyBlogs from "../blogsDefinitions/queries/getMyBlogs.js";
import type * as blogsDefinitions_queries_getPinnedBlogs from "../blogsDefinitions/queries/getPinnedBlogs.js";
import type * as blogsDefinitions_queries_getRelatedBlogs from "../blogsDefinitions/queries/getRelatedBlogs.js";
import type * as blogsDefinitions_queries_getTags from "../blogsDefinitions/queries/getTags.js";
import type * as blogsDefinitions_queries_getUserBlogInteraction from "../blogsDefinitions/queries/getUserBlogInteraction.js";
import type * as blogsDefinitions_queries_index from "../blogsDefinitions/queries/index.js";
import type * as crons from "../crons.js";
import type * as dashboard from "../dashboard.js";
import type * as email from "../email.js";
import type * as emailDirect from "../emailDirect.js";
import type * as events from "../events.js";
import type * as eventsDefinitions_index from "../eventsDefinitions/index.js";
import type * as eventsDefinitions_mutations_createEvent from "../eventsDefinitions/mutations/createEvent.js";
import type * as eventsDefinitions_mutations_createFeedbackForm from "../eventsDefinitions/mutations/createFeedbackForm.js";
import type * as eventsDefinitions_mutations_deleteEvent from "../eventsDefinitions/mutations/deleteEvent.js";
import type * as eventsDefinitions_mutations_index from "../eventsDefinitions/mutations/index.js";
import type * as eventsDefinitions_mutations_rateOrganizer from "../eventsDefinitions/mutations/rateOrganizer.js";
import type * as eventsDefinitions_mutations_registerForEvent from "../eventsDefinitions/mutations/registerForEvent.js";
import type * as eventsDefinitions_mutations_submitFeedbackResponse from "../eventsDefinitions/mutations/submitFeedbackResponse.js";
import type * as eventsDefinitions_mutations_submitFeedbackResponsePublic from "../eventsDefinitions/mutations/submitFeedbackResponsePublic.js";
import type * as eventsDefinitions_mutations_submitOrganizerRatingPublic from "../eventsDefinitions/mutations/submitOrganizerRatingPublic.js";
import type * as eventsDefinitions_mutations_toggleEventSession from "../eventsDefinitions/mutations/toggleEventSession.js";
import type * as eventsDefinitions_mutations_unregisterFromEvent from "../eventsDefinitions/mutations/unregisterFromEvent.js";
import type * as eventsDefinitions_mutations_updateEvent from "../eventsDefinitions/mutations/updateEvent.js";
import type * as eventsDefinitions_mutations_updateFeedbackForm from "../eventsDefinitions/mutations/updateFeedbackForm.js";
import type * as eventsDefinitions_mutations_uploadEventImage from "../eventsDefinitions/mutations/uploadEventImage.js";
import type * as eventsDefinitions_queries_checkFeedbackStatus from "../eventsDefinitions/queries/checkFeedbackStatus.js";
import type * as eventsDefinitions_queries_debugFeedbackForms from "../eventsDefinitions/queries/debugFeedbackForms.js";
import type * as eventsDefinitions_queries_getEventAttendees from "../eventsDefinitions/queries/getEventAttendees.js";
import type * as eventsDefinitions_queries_getEventBySlug from "../eventsDefinitions/queries/getEventBySlug.js";
import type * as eventsDefinitions_queries_getEventFeedbackResponses from "../eventsDefinitions/queries/getEventFeedbackResponses.js";
import type * as eventsDefinitions_queries_getEventSessions from "../eventsDefinitions/queries/getEventSessions.js";
import type * as eventsDefinitions_queries_getEventWithFeedbackFormPublic from "../eventsDefinitions/queries/getEventWithFeedbackFormPublic.js";
import type * as eventsDefinitions_queries_getEvents from "../eventsDefinitions/queries/getEvents.js";
import type * as eventsDefinitions_queries_getFeedbackForm from "../eventsDefinitions/queries/getFeedbackForm.js";
import type * as eventsDefinitions_queries_getMyAttendedEvents from "../eventsDefinitions/queries/getMyAttendedEvents.js";
import type * as eventsDefinitions_queries_getMyCreatedEvents from "../eventsDefinitions/queries/getMyCreatedEvents.js";
import type * as eventsDefinitions_queries_getOrganizerStatistics from "../eventsDefinitions/queries/getOrganizerStatistics.js";
import type * as eventsDefinitions_queries_getPinnedEvents from "../eventsDefinitions/queries/getPinnedEvents.js";
import type * as eventsDefinitions_queries_index from "../eventsDefinitions/queries/index.js";
import type * as facilities from "../facilities.js";
import type * as facilitiesDefinitions_index from "../facilitiesDefinitions/index.js";
import type * as facilitiesDefinitions_mutations_createFacility from "../facilitiesDefinitions/mutations/createFacility.js";
import type * as facilitiesDefinitions_mutations_endFacilitySession from "../facilitiesDefinitions/mutations/endFacilitySession.js";
import type * as facilitiesDefinitions_mutations_index from "../facilitiesDefinitions/mutations/index.js";
import type * as facilitiesDefinitions_mutations_startFacilitySession from "../facilitiesDefinitions/mutations/startFacilitySession.js";
import type * as facilitiesDefinitions_mutations_toggleFacilityAccess from "../facilitiesDefinitions/mutations/toggleFacilityAccess.js";
import type * as facilitiesDefinitions_mutations_updateFacility from "../facilitiesDefinitions/mutations/updateFacility.js";
import type * as facilitiesDefinitions_queries_getActiveSessions from "../facilitiesDefinitions/queries/getActiveSessions.js";
import type * as facilitiesDefinitions_queries_getFacilities from "../facilitiesDefinitions/queries/getFacilities.js";
import type * as facilitiesDefinitions_queries_getFacilityById from "../facilitiesDefinitions/queries/getFacilityById.js";
import type * as facilitiesDefinitions_queries_getFacilityUsageHistory from "../facilitiesDefinitions/queries/getFacilityUsageHistory.js";
import type * as facilitiesDefinitions_queries_index from "../facilitiesDefinitions/queries/index.js";
import type * as helpers from "../helpers.js";
import type * as http from "../http.js";
import type * as migrate from "../migrate.js";
import type * as migration from "../migration.js";
import type * as projects from "../projects.js";
import type * as projectsDefinitions_index from "../projectsDefinitions/index.js";
import type * as projectsDefinitions_mutations_createProject from "../projectsDefinitions/mutations/createProject.js";
import type * as projectsDefinitions_mutations_createRole from "../projectsDefinitions/mutations/createRole.js";
import type * as projectsDefinitions_mutations_index from "../projectsDefinitions/mutations/index.js";
import type * as projectsDefinitions_mutations_joinProject from "../projectsDefinitions/mutations/joinProject.js";
import type * as projectsDefinitions_mutations_reactivateProjectMember from "../projectsDefinitions/mutations/reactivateProjectMember.js";
import type * as projectsDefinitions_mutations_removeProjectMember from "../projectsDefinitions/mutations/removeProjectMember.js";
import type * as projectsDefinitions_mutations_reviewApplication from "../projectsDefinitions/mutations/reviewApplication.js";
import type * as projectsDefinitions_mutations_saveProject from "../projectsDefinitions/mutations/saveProject.js";
import type * as projectsDefinitions_mutations_toggleProjectFeatured from "../projectsDefinitions/mutations/toggleProjectFeatured.js";
import type * as projectsDefinitions_mutations_unsaveProject from "../projectsDefinitions/mutations/unsaveProject.js";
import type * as projectsDefinitions_mutations_updateProject from "../projectsDefinitions/mutations/updateProject.js";
import type * as projectsDefinitions_notifications from "../projectsDefinitions/notifications.js";
import type * as projectsDefinitions_notifications_actions from "../projectsDefinitions/notifications_actions.js";
import type * as projectsDefinitions_notifications_mutations from "../projectsDefinitions/notifications_mutations.js";
import type * as projectsDefinitions_notifications_queries from "../projectsDefinitions/notifications_queries.js";
import type * as projectsDefinitions_queries_getFeaturedProjects from "../projectsDefinitions/queries/getFeaturedProjects.js";
import type * as projectsDefinitions_queries_getMyApplications from "../projectsDefinitions/queries/getMyApplications.js";
import type * as projectsDefinitions_queries_getMyProjects from "../projectsDefinitions/queries/getMyProjects.js";
import type * as projectsDefinitions_queries_getPinnedProjects from "../projectsDefinitions/queries/getPinnedProjects.js";
import type * as projectsDefinitions_queries_getProjectBySlug from "../projectsDefinitions/queries/getProjectBySlug.js";
import type * as projectsDefinitions_queries_getProjects from "../projectsDefinitions/queries/getProjects.js";
import type * as projectsDefinitions_queries_getRoleBySlug from "../projectsDefinitions/queries/getRoleBySlug.js";
import type * as projectsDefinitions_queries_getRoles from "../projectsDefinitions/queries/getRoles.js";
import type * as projectsDefinitions_queries_getSavedProjects from "../projectsDefinitions/queries/getSavedProjects.js";
import type * as projectsDefinitions_queries_index from "../projectsDefinitions/queries/index.js";
import type * as users from "../users.js";
import type * as usersDefinitions_index from "../usersDefinitions/index.js";
import type * as usersDefinitions_mutations_adminRegisterRfidCard from "../usersDefinitions/mutations/adminRegisterRfidCard.js";
import type * as usersDefinitions_mutations_adminUpdateUser from "../usersDefinitions/mutations/adminUpdateUser.js";
import type * as usersDefinitions_mutations_createUser from "../usersDefinitions/mutations/createUser.js";
import type * as usersDefinitions_mutations_index from "../usersDefinitions/mutations/index.js";
import type * as usersDefinitions_mutations_registerRfidCard from "../usersDefinitions/mutations/registerRfidCard.js";
import type * as usersDefinitions_mutations_resendEmailVerification from "../usersDefinitions/mutations/resendEmailVerification.js";
import type * as usersDefinitions_mutations_rfidLogin from "../usersDefinitions/mutations/rfidLogin.js";
import type * as usersDefinitions_mutations_sendInitialEmailVerification from "../usersDefinitions/mutations/sendInitialEmailVerification.js";
import type * as usersDefinitions_mutations_updateCurrentUser from "../usersDefinitions/mutations/updateCurrentUser.js";
import type * as usersDefinitions_mutations_uploadProfilePicture from "../usersDefinitions/mutations/uploadProfilePicture.js";
import type * as usersDefinitions_mutations_verifyEmail from "../usersDefinitions/mutations/verifyEmail.js";
import type * as usersDefinitions_queries_getCurrentUser from "../usersDefinitions/queries/getCurrentUser.js";
import type * as usersDefinitions_queries_getUserById from "../usersDefinitions/queries/getUserById.js";
import type * as usersDefinitions_queries_getUserVerificationStatus from "../usersDefinitions/queries/getUserVerificationStatus.js";
import type * as usersDefinitions_queries_getUsers from "../usersDefinitions/queries/getUsers.js";
import type * as usersDefinitions_queries_getUsersPaginated from "../usersDefinitions/queries/getUsersPaginated.js";
import type * as usersDefinitions_queries_index from "../usersDefinitions/queries/index.js";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  ResendOTP: typeof ResendOTP;
  ResendOTPPasswordReset: typeof ResendOTPPasswordReset;
  auth: typeof auth;
  "authDefinitions/index": typeof authDefinitions_index;
  blogs: typeof blogs;
  "blogsDefinitions/index": typeof blogsDefinitions_index;
  "blogsDefinitions/mutations/archiveBlog": typeof blogsDefinitions_mutations_archiveBlog;
  "blogsDefinitions/mutations/bookmarkBlog": typeof blogsDefinitions_mutations_bookmarkBlog;
  "blogsDefinitions/mutations/createBlog": typeof blogsDefinitions_mutations_createBlog;
  "blogsDefinitions/mutations/createComment": typeof blogsDefinitions_mutations_createComment;
  "blogsDefinitions/mutations/deleteBlog": typeof blogsDefinitions_mutations_deleteBlog;
  "blogsDefinitions/mutations/deleteComment": typeof blogsDefinitions_mutations_deleteComment;
  "blogsDefinitions/mutations/featureBlog": typeof blogsDefinitions_mutations_featureBlog;
  "blogsDefinitions/mutations/flagBlog": typeof blogsDefinitions_mutations_flagBlog;
  "blogsDefinitions/mutations/flagComment": typeof blogsDefinitions_mutations_flagComment;
  "blogsDefinitions/mutations/index": typeof blogsDefinitions_mutations_index;
  "blogsDefinitions/mutations/likeBlog": typeof blogsDefinitions_mutations_likeBlog;
  "blogsDefinitions/mutations/likeComment": typeof blogsDefinitions_mutations_likeComment;
  "blogsDefinitions/mutations/moderateBlog": typeof blogsDefinitions_mutations_moderateBlog;
  "blogsDefinitions/mutations/pinBlog": typeof blogsDefinitions_mutations_pinBlog;
  "blogsDefinitions/mutations/publishBlog": typeof blogsDefinitions_mutations_publishBlog;
  "blogsDefinitions/mutations/reviewFlag": typeof blogsDefinitions_mutations_reviewFlag;
  "blogsDefinitions/mutations/shareBlog": typeof blogsDefinitions_mutations_shareBlog;
  "blogsDefinitions/mutations/unbookmarkBlog": typeof blogsDefinitions_mutations_unbookmarkBlog;
  "blogsDefinitions/mutations/unlikeBlog": typeof blogsDefinitions_mutations_unlikeBlog;
  "blogsDefinitions/mutations/unpublishBlog": typeof blogsDefinitions_mutations_unpublishBlog;
  "blogsDefinitions/mutations/updateBlog": typeof blogsDefinitions_mutations_updateBlog;
  "blogsDefinitions/mutations/uploadBlogCover": typeof blogsDefinitions_mutations_uploadBlogCover;
  "blogsDefinitions/mutations/viewBlog": typeof blogsDefinitions_mutations_viewBlog;
  "blogsDefinitions/queries/getBlogBySlug": typeof blogsDefinitions_queries_getBlogBySlug;
  "blogsDefinitions/queries/getBlogFlags": typeof blogsDefinitions_queries_getBlogFlags;
  "blogsDefinitions/queries/getBlogOverallStats": typeof blogsDefinitions_queries_getBlogOverallStats;
  "blogsDefinitions/queries/getBlogStats": typeof blogsDefinitions_queries_getBlogStats;
  "blogsDefinitions/queries/getBlogs": typeof blogsDefinitions_queries_getBlogs;
  "blogsDefinitions/queries/getCategories": typeof blogsDefinitions_queries_getCategories;
  "blogsDefinitions/queries/getCommentReplies": typeof blogsDefinitions_queries_getCommentReplies;
  "blogsDefinitions/queries/getCommentsForBlog": typeof blogsDefinitions_queries_getCommentsForBlog;
  "blogsDefinitions/queries/getFeaturedBlogs": typeof blogsDefinitions_queries_getFeaturedBlogs;
  "blogsDefinitions/queries/getMyBlogs": typeof blogsDefinitions_queries_getMyBlogs;
  "blogsDefinitions/queries/getPinnedBlogs": typeof blogsDefinitions_queries_getPinnedBlogs;
  "blogsDefinitions/queries/getRelatedBlogs": typeof blogsDefinitions_queries_getRelatedBlogs;
  "blogsDefinitions/queries/getTags": typeof blogsDefinitions_queries_getTags;
  "blogsDefinitions/queries/getUserBlogInteraction": typeof blogsDefinitions_queries_getUserBlogInteraction;
  "blogsDefinitions/queries/index": typeof blogsDefinitions_queries_index;
  crons: typeof crons;
  dashboard: typeof dashboard;
  email: typeof email;
  emailDirect: typeof emailDirect;
  events: typeof events;
  "eventsDefinitions/index": typeof eventsDefinitions_index;
  "eventsDefinitions/mutations/createEvent": typeof eventsDefinitions_mutations_createEvent;
  "eventsDefinitions/mutations/createFeedbackForm": typeof eventsDefinitions_mutations_createFeedbackForm;
  "eventsDefinitions/mutations/deleteEvent": typeof eventsDefinitions_mutations_deleteEvent;
  "eventsDefinitions/mutations/index": typeof eventsDefinitions_mutations_index;
  "eventsDefinitions/mutations/rateOrganizer": typeof eventsDefinitions_mutations_rateOrganizer;
  "eventsDefinitions/mutations/registerForEvent": typeof eventsDefinitions_mutations_registerForEvent;
  "eventsDefinitions/mutations/submitFeedbackResponse": typeof eventsDefinitions_mutations_submitFeedbackResponse;
  "eventsDefinitions/mutations/submitFeedbackResponsePublic": typeof eventsDefinitions_mutations_submitFeedbackResponsePublic;
  "eventsDefinitions/mutations/submitOrganizerRatingPublic": typeof eventsDefinitions_mutations_submitOrganizerRatingPublic;
  "eventsDefinitions/mutations/toggleEventSession": typeof eventsDefinitions_mutations_toggleEventSession;
  "eventsDefinitions/mutations/unregisterFromEvent": typeof eventsDefinitions_mutations_unregisterFromEvent;
  "eventsDefinitions/mutations/updateEvent": typeof eventsDefinitions_mutations_updateEvent;
  "eventsDefinitions/mutations/updateFeedbackForm": typeof eventsDefinitions_mutations_updateFeedbackForm;
  "eventsDefinitions/mutations/uploadEventImage": typeof eventsDefinitions_mutations_uploadEventImage;
  "eventsDefinitions/queries/checkFeedbackStatus": typeof eventsDefinitions_queries_checkFeedbackStatus;
  "eventsDefinitions/queries/debugFeedbackForms": typeof eventsDefinitions_queries_debugFeedbackForms;
  "eventsDefinitions/queries/getEventAttendees": typeof eventsDefinitions_queries_getEventAttendees;
  "eventsDefinitions/queries/getEventBySlug": typeof eventsDefinitions_queries_getEventBySlug;
  "eventsDefinitions/queries/getEventFeedbackResponses": typeof eventsDefinitions_queries_getEventFeedbackResponses;
  "eventsDefinitions/queries/getEventSessions": typeof eventsDefinitions_queries_getEventSessions;
  "eventsDefinitions/queries/getEventWithFeedbackFormPublic": typeof eventsDefinitions_queries_getEventWithFeedbackFormPublic;
  "eventsDefinitions/queries/getEvents": typeof eventsDefinitions_queries_getEvents;
  "eventsDefinitions/queries/getFeedbackForm": typeof eventsDefinitions_queries_getFeedbackForm;
  "eventsDefinitions/queries/getMyAttendedEvents": typeof eventsDefinitions_queries_getMyAttendedEvents;
  "eventsDefinitions/queries/getMyCreatedEvents": typeof eventsDefinitions_queries_getMyCreatedEvents;
  "eventsDefinitions/queries/getOrganizerStatistics": typeof eventsDefinitions_queries_getOrganizerStatistics;
  "eventsDefinitions/queries/getPinnedEvents": typeof eventsDefinitions_queries_getPinnedEvents;
  "eventsDefinitions/queries/index": typeof eventsDefinitions_queries_index;
  facilities: typeof facilities;
  "facilitiesDefinitions/index": typeof facilitiesDefinitions_index;
  "facilitiesDefinitions/mutations/createFacility": typeof facilitiesDefinitions_mutations_createFacility;
  "facilitiesDefinitions/mutations/endFacilitySession": typeof facilitiesDefinitions_mutations_endFacilitySession;
  "facilitiesDefinitions/mutations/index": typeof facilitiesDefinitions_mutations_index;
  "facilitiesDefinitions/mutations/startFacilitySession": typeof facilitiesDefinitions_mutations_startFacilitySession;
  "facilitiesDefinitions/mutations/toggleFacilityAccess": typeof facilitiesDefinitions_mutations_toggleFacilityAccess;
  "facilitiesDefinitions/mutations/updateFacility": typeof facilitiesDefinitions_mutations_updateFacility;
  "facilitiesDefinitions/queries/getActiveSessions": typeof facilitiesDefinitions_queries_getActiveSessions;
  "facilitiesDefinitions/queries/getFacilities": typeof facilitiesDefinitions_queries_getFacilities;
  "facilitiesDefinitions/queries/getFacilityById": typeof facilitiesDefinitions_queries_getFacilityById;
  "facilitiesDefinitions/queries/getFacilityUsageHistory": typeof facilitiesDefinitions_queries_getFacilityUsageHistory;
  "facilitiesDefinitions/queries/index": typeof facilitiesDefinitions_queries_index;
  helpers: typeof helpers;
  http: typeof http;
  migrate: typeof migrate;
  migration: typeof migration;
  projects: typeof projects;
  "projectsDefinitions/index": typeof projectsDefinitions_index;
  "projectsDefinitions/mutations/createProject": typeof projectsDefinitions_mutations_createProject;
  "projectsDefinitions/mutations/createRole": typeof projectsDefinitions_mutations_createRole;
  "projectsDefinitions/mutations/index": typeof projectsDefinitions_mutations_index;
  "projectsDefinitions/mutations/joinProject": typeof projectsDefinitions_mutations_joinProject;
  "projectsDefinitions/mutations/reactivateProjectMember": typeof projectsDefinitions_mutations_reactivateProjectMember;
  "projectsDefinitions/mutations/removeProjectMember": typeof projectsDefinitions_mutations_removeProjectMember;
  "projectsDefinitions/mutations/reviewApplication": typeof projectsDefinitions_mutations_reviewApplication;
  "projectsDefinitions/mutations/saveProject": typeof projectsDefinitions_mutations_saveProject;
  "projectsDefinitions/mutations/toggleProjectFeatured": typeof projectsDefinitions_mutations_toggleProjectFeatured;
  "projectsDefinitions/mutations/unsaveProject": typeof projectsDefinitions_mutations_unsaveProject;
  "projectsDefinitions/mutations/updateProject": typeof projectsDefinitions_mutations_updateProject;
  "projectsDefinitions/notifications": typeof projectsDefinitions_notifications;
  "projectsDefinitions/notifications_actions": typeof projectsDefinitions_notifications_actions;
  "projectsDefinitions/notifications_mutations": typeof projectsDefinitions_notifications_mutations;
  "projectsDefinitions/notifications_queries": typeof projectsDefinitions_notifications_queries;
  "projectsDefinitions/queries/getFeaturedProjects": typeof projectsDefinitions_queries_getFeaturedProjects;
  "projectsDefinitions/queries/getMyApplications": typeof projectsDefinitions_queries_getMyApplications;
  "projectsDefinitions/queries/getMyProjects": typeof projectsDefinitions_queries_getMyProjects;
  "projectsDefinitions/queries/getPinnedProjects": typeof projectsDefinitions_queries_getPinnedProjects;
  "projectsDefinitions/queries/getProjectBySlug": typeof projectsDefinitions_queries_getProjectBySlug;
  "projectsDefinitions/queries/getProjects": typeof projectsDefinitions_queries_getProjects;
  "projectsDefinitions/queries/getRoleBySlug": typeof projectsDefinitions_queries_getRoleBySlug;
  "projectsDefinitions/queries/getRoles": typeof projectsDefinitions_queries_getRoles;
  "projectsDefinitions/queries/getSavedProjects": typeof projectsDefinitions_queries_getSavedProjects;
  "projectsDefinitions/queries/index": typeof projectsDefinitions_queries_index;
  users: typeof users;
  "usersDefinitions/index": typeof usersDefinitions_index;
  "usersDefinitions/mutations/adminRegisterRfidCard": typeof usersDefinitions_mutations_adminRegisterRfidCard;
  "usersDefinitions/mutations/adminUpdateUser": typeof usersDefinitions_mutations_adminUpdateUser;
  "usersDefinitions/mutations/createUser": typeof usersDefinitions_mutations_createUser;
  "usersDefinitions/mutations/index": typeof usersDefinitions_mutations_index;
  "usersDefinitions/mutations/registerRfidCard": typeof usersDefinitions_mutations_registerRfidCard;
  "usersDefinitions/mutations/resendEmailVerification": typeof usersDefinitions_mutations_resendEmailVerification;
  "usersDefinitions/mutations/rfidLogin": typeof usersDefinitions_mutations_rfidLogin;
  "usersDefinitions/mutations/sendInitialEmailVerification": typeof usersDefinitions_mutations_sendInitialEmailVerification;
  "usersDefinitions/mutations/updateCurrentUser": typeof usersDefinitions_mutations_updateCurrentUser;
  "usersDefinitions/mutations/uploadProfilePicture": typeof usersDefinitions_mutations_uploadProfilePicture;
  "usersDefinitions/mutations/verifyEmail": typeof usersDefinitions_mutations_verifyEmail;
  "usersDefinitions/queries/getCurrentUser": typeof usersDefinitions_queries_getCurrentUser;
  "usersDefinitions/queries/getUserById": typeof usersDefinitions_queries_getUserById;
  "usersDefinitions/queries/getUserVerificationStatus": typeof usersDefinitions_queries_getUserVerificationStatus;
  "usersDefinitions/queries/getUsers": typeof usersDefinitions_queries_getUsers;
  "usersDefinitions/queries/getUsersPaginated": typeof usersDefinitions_queries_getUsersPaginated;
  "usersDefinitions/queries/index": typeof usersDefinitions_queries_index;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
